import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import "./calendar.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner"

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Inkspo",
    description: "Generated by GPT",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <SessionProvider>
                    {children}
                    <Toaster className={`${inter.className}`} richColors={false} position="top-center"/>
                </SessionProvider>
            </body>
        </html>
    );
}
